module.exports = {
  "cities": [
    { "name": "Amsterdam", "image": "Passport_Amsterdam_IBiascRRg.png" },
    { "name": "Dallas", "image": "Passport_Dallas_4eQemCXazx.png" },
    { "name": "Syracuse", "image": "Passport_Syracuse_Nf9o7dOcdN.png" },
    { "name": "Atlanta", "image": "Passport_Atlanta_2utUhfB8uF.png" },
    { "name": "Austin", "image": "Passport_Austin_FK1Suzbkfn.png" },
    { "name": "Baltimore", "image": "Passport_Baltimore_ZK0YiWuwRW.png" },
    { "name": "Boston", "image": "Passport_Boston_R1xctRBasS.png" },
    { "name": "Brooklyn", "image": "Passport_Brooklyn_3wXeOVBEa.png" },
    { "name": "Buffalo", "image": "Passport_Buffalo_EFKsYE1y_y.png" },
    { "name": "Chicago", "image": "Passport_Chicago_CYUkF3_ZbT.png" },
    { "name": "Denver", "image": "Passport_Denver_XtxD-VyUbv.png" },
    { "name": "Edmonton", "image": "Passport_Edmonton_kRezp9ZZLu.png" },
    { "name": "Grand Rapids", "image": "Passport_Grand_Rapids_u4b8MJfHu5.png" },
    { "name": "Hong Kong", "image": "Passport_Hong_Kong_YJR9P9a7MQ.png" },
    { "name": "Iceland", "image": "Passport_Iceland_-jxhhv7IR.png" },
    { "name": "Indianapolis", "image": "Passport_Indianapolis_IQ82HUHFyj.png" },
    { "name": "Kansas City", "image": "Passport_Kansas_City_JRSGCgffHi.png" },
    { "name": "Kelowna", "image": "Passport_Kelowna_S9U2316MDQ.png" },
    { "name": "London", "image": "Passport_London_CqYjEk4O9U.png" },
    { "name": "Los Angeles", "image": "Passport_Los_Angeles_oSFNwIXyF.png" },
    { "name": "Madison", "image": "Passport_Madison_d_ATYDCz6G.png" },
    { "name": "Malaysia", "image": "Passport_Malaysia_BSgQilLV5d.png" },
    { "name": "Milwaukee", "image": "Passport_Milwaukee_xghacVkY1i.png" },
    { "name": "Minneapolis", "image": "Passport_Minneapolis_EMq36Fof4z.png" },
    { "name": "Montreal", "image": "Passport_Montreal_Lkr_8xGMBg.png" },
    { "name": "New Orleans", "image": "Passport_New_Orleans_XHnQbf04z5.png" },
    { "name": "New York City", "image": "Passport_New_York_City_HioOeZ4EUh.png" },
    { "name": "Newport", "image": "Passport_Newport_7fZGdbajL4.png" },
    { "name": "Novi Sad", "image": "Passport_Novi_Sad_20i2VSZV4.png" },
    { "name": "Oakland", "image": "Passport_Oakland_iMYw93cmoV.png" },
    { "name": "Orlando", "image": "Passport_Orlando_8yqMg0eS0.png" },
    { "name": "Ottawa", "image": "Passport_Ottawa_zFSkzNX_v2.png" },
    { "name": "Philadelphia", "image": "Passport_Philadelphia_O9AgSQRnCE.png" },
    { "name": "Phoenix", "image": "Passport_Phoenix_VHLye0zToo.png" },
    { "name": "Portland", "image": "Passport_Portland_MX0jNzX1k.png" },
    { "name": "Providence", "image": "Passport_Providence_woohuBYS_b.png" },
    { "name": "Queen City", "image": "Passport_Queen_City_C9uNmWZoOd.png" },
    { "name": "Richmond", "image": "Passport_Richmond_WT4-UCwW2f.png" },
    { "name": "San Diego", "image": "Passport_San_Diego_3D4j2d94X-.png" },
    { "name": "San Francisco", "image": "Passport_San_Francisco_D40MQTSKr.png" },
    { "name": "Seattle", "image": "Passport_Seattle_idS8exy-ye.png" },
    { "name": "Toronto", "image": "Passport_Toronto_wJE-euswJJ.png" },
    { "name": "Vancouver", "image": "Passport_Vancouver_Nb4hq3fXD7.png" },
    { "name": "Victoria", "image": "Passport_Victoria_O3KSHzzmAa.png" },
    { "name": "Virginia Beach", "image": "Passport_Virginia_Beach_6eT1ZYh-5C.png" },
    { "name": "Washington", "image": "Passport_Washington_DC_LXA9nTgeN1.png" },
    { "name": "West Los Angeles", "image": "Passport_West_Los_Angeles_Na_3XhpHes.png" },
    { "name": "Winnipeg", "image": "Passport_Winnipeg_pl2mgmbo8A.png" },
    { "name": "Worcester", "image": "Passport_Worcester_j3_zE6aFI.png" }
  ]
};
